"""empty message

Revision ID: c270034287a1
Revises: 
Create Date: 2023-07-20 13:59:22.248020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c270034287a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emanets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deposit_type', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('surname', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kampaniyalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.String(length=25), nullable=True),
    sa.Column('date1', sa.String(length=25), nullable=True),
    sa.Column('date2', sa.String(length=25), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('kategori', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onlinenovbe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filial', sa.String(length=100), nullable=True),
    sa.Column('xidmet_novu', sa.String(length=100), nullable=True),
    sa.Column('tarix', sa.String(length=100), nullable=True),
    sa.Column('vaxt', sa.String(length=100), nullable=True),
    sa.Column('mobil_nomre', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('universalemanetler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('basliq', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('muddet', sa.String(length=255), nullable=False),
    sa.Column('faiz', sa.String(length=255), nullable=False),
    sa.Column('valyuta', sa.String(length=255), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xeberler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('basliq', sa.String(length=255), nullable=False),
    sa.Column('img', sa.String(length=255), nullable=False),
    sa.Column('tarix', sa.String(length=255), nullable=False),
    sa.Column('kategori', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('details_img', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xeberler')
    op.drop_table('users')
    op.drop_table('universalemanetler')
    op.drop_table('onlinenovbe')
    op.drop_table('kampaniyalar')
    op.drop_table('emanets')
    # ### end Alembic commands ###
