"""empty message

Revision ID: f931c56548de
Revises: c270034287a1
Create Date: 2023-07-20 15:33:27.321783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f931c56548de'
down_revision = 'c270034287a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emanets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit', sa.String(length=255), nullable=True))
        batch_op.drop_column('deposit_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emanets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit_type', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('deposit')

    # ### end Alembic commands ###
